// api/_seed.js
// Dados iniciais do Canil de Vilhena.
// Os pets referenciam fotos de uploads/pets/ (Wikimedia Commons, licenca livre),
// catalogadas em uploads/indice-fotos.json.
//
// Este arquivo e a fonte da verdade do banco: rodar `npm run seed` recria
// db/canil.sqlite com todo o conteudo de demonstracao.

const foto = (arquivo) => `uploads/pets/${arquivo}`;

const PETS = [
  {
    id: 'pet-nina',
    nome: 'Nina',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 2,
    porte: 'Médio',
    sexo: 'Fêmea',
    status: 'disponível',
    energia: 'Alta',
    temperamento: 'Brincalhona, sociável e muito carinhosa',
    vacinado: true,
    castrado: true,
    descricao:
      'Nina ama passeios, se dá bem com outros cães e adora pessoas. Excelente para famílias ativas e casas com quintal.',
    bairroResgate: 'Cristo Rei',
    observacaoInterna: 'Responde bem ao treino com petiscos. Evitar longos períodos sozinha.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [
      foto('a-playful-set-of-dogs-on-a-beach.jpg'),
      foto('agnes-the-golden-retriever.jpg'),
      foto('a-golden-retriever-barras.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 45, zoom: 1.14, brilho: 106, contraste: 106, saturacao: 115 },
    criadoEm: '2026-01-12T09:00:00.000Z',
    atualizadoEm: '2026-09-18T10:18:00.000Z',
  },
  {
    id: 'pet-luke',
    nome: 'Luke',
    especie: 'cão',
    raca: 'Pastor Alemão',
    idade: 4,
    porte: 'Grande',
    sexo: 'Macho',
    status: 'em tratamento',
    energia: 'Média',
    temperamento: 'Leal, atento e calmo no dia a dia',
    vacinado: true,
    castrado: false,
    descricao:
      'Luke foi resgatado recentemente e está em recuperação de pele. Já aceita coleira e responde a comandos básicos.',
    bairroResgate: 'Jardim América',
    observacaoInterna: 'Manter medicação dermatológica até liberação veterinária.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('1yearoldgermanshepherd.jpg'), foto('a-german-shepherd-sniffing-a-beagle.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 52, y: 38, zoom: 1.2, brilho: 100, contraste: 103, saturacao: 102 },
    criadoEm: '2026-01-18T09:00:00.000Z',
    atualizadoEm: '2026-09-17T08:02:00.000Z',
  },
  {
    id: 'pet-luna',
    nome: 'Luna',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 1.5,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'disponível',
    energia: 'Média',
    temperamento: 'Curiosa, dócil e muito observadora',
    vacinado: true,
    castrado: true,
    descricao:
      'Luna gosta de ambientes tranquilos, usa caixa de areia e se adapta bem a apartamentos com rotina previsível.',
    bairroResgate: 'Bela Vista',
    observacaoInterna: 'Acompanha bem com enriquecimento ambiental e arranhador vertical.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [
      foto('a-sleeping-young-tabby-cat.jpg'),
      foto('pandora-tabby-cat.jpg'),
      foto('blotched-tabby-bullseye.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 44, zoom: 1.16, brilho: 108, contraste: 108, saturacao: 120 },
    criadoEm: '2026-01-22T09:00:00.000Z',
    atualizadoEm: '2026-09-16T16:30:00.000Z',
  },
  {
    id: 'pet-bento',
    nome: 'Bento',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 0.8,
    porte: 'Pequeno',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Alta',
    temperamento: 'Divertido, esperto e cheio de energia',
    vacinado: true,
    castrado: false,
    descricao:
      'Bento é um filhote ativo, adora brincar e aprende rápido. Ideal para quem tem tempo para interação diária.',
    bairroResgate: 'São José',
    observacaoInterna: 'Treino de socialização em andamento. Já responde ao nome.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('alfa1.jpg'), foto('alfa2.jpg'), foto('alfa3.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 48, y: 46, zoom: 1.22, brilho: 111, contraste: 110, saturacao: 124 },
    criadoEm: '2026-02-02T09:00:00.000Z',
    atualizadoEm: '2026-09-15T13:42:00.000Z',
  },
  {
    id: 'pet-bidu',
    nome: 'Bidu',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 1.2,
    porte: 'Pequeno',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Média',
    temperamento: 'Sociável, curioso e afetuoso',
    vacinado: true,
    castrado: true,
    descricao: 'Bidu adora companhia e passeios curtos. Excelente para apartamento com rotina estável.',
    bairroResgate: 'Centro',
    observacaoInterna: 'Boa adaptação com guia peitoral.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('panoramio-badsanta23-34.jpg'), foto('panoramio-badsanta23-36.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 46, zoom: 1.12, brilho: 107, contraste: 106, saturacao: 114 },
    criadoEm: '2026-02-10T09:00:00.000Z',
    atualizadoEm: '2026-09-14T10:20:00.000Z',
  },
  {
    id: 'pet-frida',
    nome: 'Frida',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 2.4,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'disponível',
    energia: 'Baixa',
    temperamento: 'Calma, observadora e dócil',
    vacinado: true,
    castrado: true,
    descricao: 'Frida gosta de ambientes silenciosos e rotina previsível. Ideal para companhia tranquila.',
    bairroResgate: 'Nova Esperança',
    observacaoInterna: 'Adaptação ótima com arranhador e caixa de areia higiênica.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('kittby.jpg'), foto('catinbox.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 52, y: 42, zoom: 1.15, brilho: 103, contraste: 104, saturacao: 109 },
    criadoEm: '2026-02-11T09:00:00.000Z',
    atualizadoEm: '2026-09-13T08:35:00.000Z',
  },
  {
    id: 'pet-simba',
    nome: 'Simba',
    especie: 'cão',
    raca: 'Labrador',
    idade: 3.1,
    porte: 'Grande',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Média',
    temperamento: 'Companheiro, leal e brincalhão',
    vacinado: true,
    castrado: true,
    descricao: 'Simba é equilibrado e obediente. Vai bem com rotina de passeios e interação diária.',
    bairroResgate: 'São Cristóvão',
    observacaoInterna: 'Bom com crianças acima de 8 anos.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [
      foto('a-labrador-retriever-in-aurora-colorado.jpg'),
      foto('a-portrait-watson-the-golden-sit-flickr-pmarkham.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 45, zoom: 1.16, brilho: 106, contraste: 107, saturacao: 112 },
    criadoEm: '2026-02-12T09:00:00.000Z',
    atualizadoEm: '2026-09-12T16:10:00.000Z',
  },
  {
    id: 'pet-pipoca',
    nome: 'Pipoca',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 0.9,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'disponível',
    energia: 'Alta',
    temperamento: 'Brincalhona e curiosa',
    vacinado: true,
    castrado: false,
    descricao: 'Pipoca é jovem, ativa e cheia de personalidade. Ama brinquedos interativos.',
    bairroResgate: 'Parque Industrial',
    observacaoInterna: 'Em processo final para castração.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('august-kittens.jpg'), foto('baby-cute-cat.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 51, y: 43, zoom: 1.19, brilho: 109, contraste: 110, saturacao: 121 },
    criadoEm: '2026-02-14T09:00:00.000Z',
    atualizadoEm: '2026-09-11T12:44:00.000Z',
  },
  {
    id: 'pet-jorge',
    nome: 'Jorge',
    especie: 'cão',
    raca: 'Poodle',
    idade: 5,
    porte: 'Médio',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Baixa',
    temperamento: 'Calmo, companheiro e gentil',
    vacinado: true,
    castrado: true,
    descricao: 'Jorge é ideal para rotina tranquila e gosta de ficar perto das pessoas.',
    bairroResgate: 'Cidade Verde',
    observacaoInterna: 'Ótimo comportamento em ambiente interno.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('adult-poodle.jpg'), foto('a-white-dog-lay-on-rock.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 45, zoom: 1.11, brilho: 104, contraste: 103, saturacao: 104 },
    criadoEm: '2026-02-15T09:00:00.000Z',
    atualizadoEm: '2026-09-10T09:05:00.000Z',
  },
  {
    id: 'pet-farofa',
    nome: 'Farofa',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 2.7,
    porte: 'Médio',
    sexo: 'Fêmea',
    status: 'disponível',
    energia: 'Média',
    temperamento: 'Carinhosa, dócil e companheira',
    vacinado: true,
    castrado: true,
    descricao:
      'Farofa gosta de rotina tranquila, se adapta bem a famílias e adora interação com adultos e crianças.',
    bairroResgate: 'Bodanese',
    observacaoInterna: 'Boa adaptação com guia e comandos básicos.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('street-dog-03617.jpg'), foto('street-dog-03618.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 44, zoom: 1.15, brilho: 106, contraste: 106, saturacao: 112 },
    criadoEm: '2026-02-18T09:00:00.000Z',
    atualizadoEm: '2026-09-09T10:12:00.000Z',
  },
  {
    id: 'pet-tobias',
    nome: 'Tobias',
    especie: 'cão',
    raca: 'Pastor Alemão',
    idade: 1.9,
    porte: 'Pequeno',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Alta',
    temperamento: 'Brincalhão, alegre e muito sociável',
    vacinado: true,
    castrado: true,
    descricao: 'Tobias é ativo e ideal para famílias com rotina de passeios e brincadeiras diárias.',
    bairroResgate: 'Jardim Eldorado',
    observacaoInterna: 'Excelente resposta a treino com reforço positivo.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('a-dog-in-hambledon-hill.jpg'), foto('agility-slalom-5.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 49, y: 43, zoom: 1.18, brilho: 108, contraste: 109, saturacao: 118 },
    criadoEm: '2026-02-20T09:00:00.000Z',
    atualizadoEm: '2026-09-08T15:40:00.000Z',
  },
  {
    id: 'pet-bolota',
    nome: 'Bolota',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 6.1,
    porte: 'Grande',
    sexo: 'Macho',
    status: 'em tratamento',
    energia: 'Baixa',
    temperamento: 'Gentil e tranquilo',
    vacinado: true,
    castrado: false,
    descricao: 'Bolota está em recuperação veterinária e ainda não está apto para adoção.',
    bairroResgate: 'Parque Cidade Nova',
    observacaoInterna: 'Acompanhamento clínico quinzenal. Alta prevista para o próximo mês.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('3-aar-golden-hund.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 42, zoom: 1.12, brilho: 101, contraste: 102, saturacao: 103 },
    criadoEm: '2026-02-22T09:00:00.000Z',
    atualizadoEm: '2026-09-07T11:30:00.000Z',
  },
  {
    id: 'pet-maya',
    nome: 'Maya',
    especie: 'gato',
    raca: 'Persa',
    idade: 3.4,
    porte: 'Médio',
    sexo: 'Fêmea',
    status: 'disponível',
    energia: 'Baixa',
    temperamento: 'Serena e muito carinhosa',
    vacinado: true,
    castrado: true,
    descricao:
      'Maya chegou de uma ninhada resgatada e hoje é a pet mais tranquila do canil. Gosta de ficar no colo e de janelas ensolaradas.',
    bairroResgate: 'Setor Maringá',
    observacaoInterna: 'Necessita escova semanal para evitar nós no pelo.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('gato-persa.jpg'), foto('cute-persian-cat.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 42, zoom: 1.1, brilho: 105, contraste: 104, saturacao: 108 },
    criadoEm: '2026-03-05T09:00:00.000Z',
    atualizadoEm: '2026-09-06T09:40:00.000Z',
  },
  {
    id: 'pet-apollo',
    nome: 'Apolo',
    especie: 'cão',
    raca: 'Pastor Alemão',
    idade: 2.2,
    porte: 'Grande',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Alta',
    temperamento: 'Atento, protetor e muito sociável',
    vacinado: true,
    castrado: true,
    descricao:
      'Apolo tem porte grande e rotina de passeios intensa. Ideal para quem busca um cão de trabalho com temperamento estável.',
    bairroResgate: 'Jardim Bandeirantes',
    observacaoInterna: 'Precisa de tutor com experiência com cães de grande porte.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('alsesion-dog-gunturu.jpg'), foto('agility-wippe-4.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 40, zoom: 1.16, brilho: 104, contraste: 105, saturacao: 110 },
    criadoEm: '2026-03-07T09:00:00.000Z',
    atualizadoEm: '2026-09-05T14:20:00.000Z',
  },
  {
    id: 'pet-cacau',
    nome: 'Cacau',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 1.1,
    porte: 'Pequeno',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Média',
    temperamento: 'Espertinho e um pouco desconfiado no início',
    vacinado: true,
    castrado: false,
    descricao:
      'Cacau ainda está aprendendo a confiar nas pessoas. Com paciência, vira um companheiro muito carinhoso.',
    bairroResgate: 'Assentamento Vale Verde',
    observacaoInterna: 'Necessário período de adaptação sem visitantes nas primeiras semanas.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('baby-sleep.jpg'), foto('a-cat-is-curled-up-cuddling-her-kitten.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 52, y: 45, zoom: 1.12, brilho: 104, contraste: 104, saturacao: 107 },
    criadoEm: '2026-03-09T09:00:00.000Z',
    atualizadoEm: '2026-09-04T10:15:00.000Z',
  },
  {
    id: 'pet-nilo',
    nome: 'Nilo',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 1.7,
    porte: 'Médio',
    sexo: 'Macho',
    status: 'disponível',
    energia: 'Média',
    temperamento: 'Dócil, sociável e bom de convívio',
    vacinado: true,
    castrado: true,
    descricao: 'Nilo convive bem com outros animais do canil. Parceiro ideal para família ativa.',
    bairroResgate: 'Bela Vista',
    observacaoInterna: 'Convive bem na sala de convivência do canil.',
    adotante: '',
    telefoneAdotante: '',
    galeria: [foto('a-dog-beggar-panoramio.jpg'), foto('panoramio-lub0t-8.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 44, zoom: 1.13, brilho: 106, contraste: 106, saturacao: 111 },
    criadoEm: '2026-03-11T09:00:00.000Z',
    atualizadoEm: '2026-09-03T15:50:00.000Z',
  },
  {
    id: 'pet-amelie',
    nome: 'Amélie',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 3,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Baixa',
    temperamento: 'Tranquila e muito afetuosa',
    vacinado: true,
    castrado: true,
    descricao:
      'Amélie encontrou um lar e segue em acompanhamento pós-adoção com excelente adaptação.',
    bairroResgate: 'Parque São Paulo',
    observacaoInterna: 'Adoção concluída com checklist completo e orientações entregues.',
    adotante: 'Marina C.',
    telefoneAdotante: '(69) 9 9123-4400',
    galeria: [foto('cat-on-home.jpg'), foto('cat-in-sofa.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 52, y: 47, zoom: 1.1, brilho: 102, contraste: 102, saturacao: 106 },
    criadoEm: '2026-01-28T09:00:00.000Z',
    atualizadoEm: '2026-08-28T11:05:00.000Z',
    historiaAdocao:
      'A Amélie passou quase um ano no canil esperando uma casa sem outros animais. Em agosto de 2026, a Marina a buscou numa tarde de sábado. Hoje dorme na janela e acompanha a rotina da filha de 8 anos.',
    historiaTitulo: 'A Amélie esperou um ano para encontrar a Marina',
    historiaPublicado: true,
    historiaPublicadoEm: '2026-08-28T11:10:00.000Z',
    historiaAtualizadoEm: '2026-08-28T11:10:00.000Z',
  },
  {
    id: 'pet-margarida',
    nome: 'Margarida',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 4.2,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Baixa',
    temperamento: 'Calma, afetuosa e observadora',
    vacinado: true,
    castrado: true,
    descricao:
      'Margarida encontrou um lar e está em adaptação excelente, com retorno positivo da família adotante.',
    bairroResgate: 'Centro',
    observacaoInterna: 'Adoção concluída com orientações pós-adoção entregues.',
    adotante: 'Luciana e Paulo',
    telefoneAdotante: '(69) 9 9888-4421',
    galeria: [
      foto('cat-on-the-street-in-the-city-of-chefchaouen.jpg'),
      foto('ashoo.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 51, y: 45, zoom: 1.13, brilho: 104, contraste: 104, saturacao: 109 },
    criadoEm: '2026-02-03T09:00:00.000Z',
    atualizadoEm: '2026-08-25T09:10:00.000Z',
    historiaAdocao:
      'Resgatada em uma obra no Centro, a Margarida chegou filhote e hoje é a companheira de leitura da Luciana. Ela nunca mais olhou para trás.',
    historiaTitulo: 'Da rua para a poltrona: a história da Margarida',
    historiaPublicado: true,
    historiaPublicadoEm: '2026-08-25T09:15:00.000Z',
    historiaAtualizadoEm: '2026-08-25T09:15:00.000Z',
  },
  {
    id: 'pet-amora',
    nome: 'Amora',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 2.3,
    porte: 'Médio',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Média',
    temperamento: 'Doce, companheira e atenta',
    vacinado: true,
    castrado: true,
    descricao:
      'Amora foi adotada por uma família com rotina ativa e já participa de passeios diários no bairro.',
    bairroResgate: 'Jardim das Oliveiras',
    observacaoInterna: 'Adoção consolidada com retorno positivo no acompanhamento.',
    adotante: 'Família Almeida',
    telefoneAdotante: '(69) 9 9766-4012',
    galeria: [
      foto('a-golden-retriever-2-barras.jpg'),
      foto('a-golden-retriever-3-barras.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 44, zoom: 1.14, brilho: 106, contraste: 107, saturacao: 113 },
    criadoEm: '2026-02-14T09:00:00.000Z',
    atualizadoEm: '2026-08-22T09:15:00.000Z',
    historiaAdocao:
      'A Amora chegou com medo de motos e hoje puxa a selfie de cada passeio. A família Almeida conta que ela virou a rotina preferida das manhãs de sábado.',
    historiaTitulo: 'A Amora aprendeu a amar o parque do bairro',
    historiaPublicado: true,
    historiaPublicadoEm: '2026-08-22T09:20:00.000Z',
    historiaAtualizadoEm: '2026-08-22T09:20:00.000Z',
  },
  {
    id: 'pet-kiara',
    nome: 'Kiara',
    especie: 'gato',
    raca: 'Persa',
    idade: 1.8,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Média',
    temperamento: 'Afetuosa e muito curiosa',
    vacinado: true,
    castrado: true,
    descricao:
      'Kiara foi adotada por tutores experientes e está adaptada ao novo lar com enriquecimento ambiental.',
    bairroResgate: 'Centro',
    observacaoInterna: 'Adaptação excelente após a primeira semana.',
    adotante: 'Carolina e Denise',
    telefoneAdotante: '(69) 9 9881-2274',
    galeria: [foto('kucing-persia-jantan.jpg'), foto('kucing-persia-jantan-2.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 51, y: 44, zoom: 1.13, brilho: 104, contraste: 105, saturacao: 110 },
    criadoEm: '2026-02-20T09:00:00.000Z',
    atualizadoEm: '2026-08-19T14:05:00.000Z',
    historiaAdocao:
      'Kiara foi entregue ainda filhote e hoje vive com duas tutoras que prepararam cada cômodo antes da chegada. Já dorme na mesma cama que elas.',
    historiaTitulo: 'Kiara chegou filhote e hoje é irmã das tutoras',
    historiaPublicado: false,
    historiaPublicadoEm: '',
    historiaAtualizadoEm: '2026-08-19T14:05:00.000Z',
  },
  {
    id: 'pet-paco',
    nome: 'Paco',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 3.6,
    porte: 'Grande',
    sexo: 'Macho',
    status: 'adotado',
    energia: 'Baixa',
    temperamento: 'Gentil, tranquilo e obediente',
    vacinado: true,
    castrado: true,
    descricao: 'Paco ganhou um lar com quintal amplo e rotina calma, ideal para seu perfil.',
    bairroResgate: 'São José',
    observacaoInterna: 'Sem intercorrências no pós-adoção.',
    adotante: 'Rafael e Luan',
    telefoneAdotante: '(69) 9 9122-7390',
    galeria: [
      foto('a-golden-retriever-4-barras.jpg'),
      foto('a-golden-retriever-5-barras.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 49, y: 43, zoom: 1.12, brilho: 103, contraste: 104, saturacao: 106 },
    criadoEm: '2026-02-25T09:00:00.000Z',
    atualizadoEm: '2026-08-16T11:22:00.000Z',
  },
  {
    id: 'pet-mimo',
    nome: 'Mimo',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 2.1,
    porte: 'Pequeno',
    sexo: 'Macho',
    status: 'adotado',
    energia: 'Baixa',
    temperamento: 'Calmo e muito carinhoso',
    vacinado: true,
    castrado: true,
    descricao: 'Mimo foi adotado por um casal idoso e se adaptou muito bem ao ambiente interno.',
    bairroResgate: 'Jardim Eldorado',
    observacaoInterna: 'Acompanhamento finalizado com avaliação positiva.',
    adotante: 'Dona Sônia e Sr. Carlos',
    telefoneAdotante: '(69) 9 9550-1804',
    galeria: [foto('pali-cat.jpg'), foto('a-cat-with-two-kittens-in-ramat-gan.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 45, zoom: 1.12, brilho: 105, contraste: 105, saturacao: 109 },
    criadoEm: '2026-03-01T09:00:00.000Z',
    atualizadoEm: '2026-08-12T10:35:00.000Z',
  },
  {
    id: 'pet-lola',
    nome: 'Lola',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 1.5,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Alta',
    temperamento: 'Alegre e muito brincalhona',
    vacinado: true,
    castrado: true,
    descricao:
      'Lola foi adotada por família com crianças e está plenamente integrada à rotina da casa.',
    bairroResgate: 'Parque Cidade Nova',
    observacaoInterna: 'Tutor responsável e plano vacinal em dia.',
    adotante: 'Família Santos',
    telefoneAdotante: '(69) 9 9410-6721',
    galeria: [
      foto('a-golden-retriever-6-barras.jpg'),
      foto('a-golden-retriever-8-barras.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 44, zoom: 1.16, brilho: 108, contraste: 109, saturacao: 117 },
    criadoEm: '2026-03-03T09:00:00.000Z',
    atualizadoEm: '2026-08-08T16:40:00.000Z',
  },
  {
    id: 'pet-thor',
    nome: 'Thor',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 4.2,
    porte: 'Grande',
    sexo: 'Macho',
    status: 'adotado',
    energia: 'Média',
    temperamento: 'Protetor, dócil e muito familiar',
    vacinado: true,
    castrado: true,
    descricao:
      'Thor foi adotado após dois anos no canil e virou referência nas conversas sobre adoção responsible.',
    bairroResgate: 'Cristo Rei',
    observacaoInterna: 'Acompanhamento concluído com laudo veterinário normalizado.',
    adotante: 'Larissa e Family',
    telefoneAdotante: '(69) 9 9744-1290',
    galeria: [
      foto('a-golden-retriever-barking-barras.jpg'),
      foto('a-golden-retriever-9-barras.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 43, zoom: 1.14, brilho: 106, contraste: 107, saturacao: 112 },
    criadoEm: '2026-01-30T09:00:00.000Z',
    atualizadoEm: '2026-08-05T09:30:00.000Z',
    historiaAdocao:
      'Thor esperou dois anos por uma família. Quando a Larissa conheceu o canil, já tinha uma carta de apresentação escrita pela equipe técnica. Hoje divide a casa com duas crianças.',
    historiaTitulo: 'Dois anos de espera: Thor finalmente é da Larissa',
    historiaPublicado: true,
    historiaPublicadoEm: '2026-08-05T09:35:00.000Z',
    historiaAtualizadoEm: '2026-08-05T09:35:00.000Z',
  },
  {
    id: 'pet-mel',
    nome: 'Mel',
    especie: 'cão',
    raca: 'Vira-lata caramelo',
    idade: 2.8,
    porte: 'Médio',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Alta',
    temperamento: 'Animada, brincalhona e muito sociável',
    vacinado: true,
    castrado: true,
    descricao: 'Mel foi adotada pela família Rocha e é a companheira de brincadeiras das crianças.',
    bairroResgate: 'São Cristóvão',
    observacaoInterna: 'Convivência com crianças monitorada nos primeiros 90 dias.',
    adotante: 'Família Rocha',
    telefoneAdotante: '(69) 9 9300-1122',
    galeria: [
      foto('amazing-grace-gracie-seattle-seahawks-game-face.jpg'),
      foto('agility-sprung-schafer-1.jpg'),
    ],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 50, y: 44, zoom: 1.12, brilho: 107, contraste: 108, saturacao: 114 },
    criadoEm: '2026-02-08T09:00:00.000Z',
    atualizadoEm: '2026-07-30T15:00:00.000Z',
    historiaAdocao:
      'A Mel chegou com excesso de energia e hoje é a companheira preferida dos passeios da família Rocha. O laudo de comportamento do canil foi usado como referência no acompanhamento.',
    historiaTitulo: 'A Mel transformou os passeios da família Rocha',
    historiaPublicado: true,
    historiaPublicadoEm: '2026-07-30T15:05:00.000Z',
    historiaAtualizadoEm: '2026-07-30T15:05:00.000Z',
  },
  {
    id: 'pet-nala',
    nome: 'Nala',
    especie: 'gato',
    raca: 'Vira-lata caramelo',
    idade: 1.9,
    porte: 'Pequeno',
    sexo: 'Fêmea',
    status: 'adotado',
    energia: 'Média',
    temperamento: 'Curiosa e um pouco tímida',
    vacinado: true,
    castrado: true,
    descricao:
      'Nala foi adotada por quem buscava companhia para apartamento e hoje é o xodó do tutor.',
    bairroResgate: 'Jardim América',
    observacaoInterna: 'Acompanhamento encerrado com avaliação comportamental positiva.',
    adotante: 'Bruno A.',
    telefoneAdotante: '(69) 9 9201-7788',
    galeria: [foto('cats-kitten-jerusalem.jpg'), foto('cat-chews-on-bottle.jpg')],
    fotoPerfilIndex: 0,
    fotoPerfilAjuste: { x: 52, y: 46, zoom: 1.1, brilho: 104, contraste: 104, saturacao: 108 },
    criadoEm: '2026-02-26T09:00:00.000Z',
    atualizadoEm: '2026-07-25T12:10:00.000Z',
  },
];

const capaBlog = (arquivo) => `uploads/pets/${arquivo}`;

const POSTS = [
  {
    id: 'post-12',
    titulo: 'Como preparar a casa nos 7 dias antes da adoção',
    resumo:
      'Checklist prático de produtos e adaptações que evitam estresse no dia em que o pet chega.',
    categoria: 'Preparação',
    data: '2026-09-16',
    autor: 'Equipe Canil de Vilhena',
    capa: capaBlog('a-golden-retriever-3-barras.jpg'),
    publicado: true,
    conteudo:
      'Chegar preparada evita a maioria dos problemas da primeira semana. Cerque janelas e varandas, tire objetos pequenos do alcance, tenha ração e areia prontas e prepare um cantinho reservado para descanso. Nos dias seguintes, mantenha horários fixos de alimentação e passeio: é a previsibilidade que faz o animal entender que existe uma rotina nova, e não uma mudança imprevisível.',
  },
  {
    id: 'post-13',
    titulo: 'Vermífugo: o calendário básico dos filhotes',
    resumo:
      'Entenda como funciona o calendário de vermífugo conforme a idade do filhote e o histórico de vacinação.',
    categoria: 'Saúde',
    data: '2026-09-09',
    autor: 'Dra. Paula Mendes — veterinária responsável',
    capa: capaBlog('1yearoldgermanshepherd.jpg'),
    publicado: true,
    conteudo:
      'Filhotes precisam de duas a três doses de vermífugo com intervalo de 15 dias, começando ainda nas primeiras semanas de vida. A repetição mensal acontece até os seis meses. Para adultos, a recomendação é anual ou trimestral conforme a exposição a parques e áreas de solo. Vermífugo não substitui as medidas de higiene: retirar fezes com frequência reduz em grande parte a exposição do animal.',
  },
  {
    id: 'post-14',
    titulo: 'Manejo do estresse: os sinais que a equipe acompanha no dia a dia',
    resumo:
      'Como observar alterações de hábito para antecipar o estresse antes que ele vire um problema maior.',
    categoria: 'Comportamento',
    data: '2026-09-02',
    autor: 'Equipe Canil de Vilhena',
    capa: capaBlog('street-dog-03617.jpg'),
    publicado: true,
    conteudo:
      'O estresse aparece antes dos problemas graves. Bocejos repetidos fora do sono, lambidas repetidas, evitar comida em ambiente novo e ficar escondido nos cantos são sinais de alerta. Quando detectados no primeiro dia, a equipe reduz exposição, mantém previsibilidade e evita punições. Animais que passam por esse protocolo recuperam a confiança em média em sete a dez dias.',
  },
  {
    id: 'post-15',
    titulo: 'Castração: o que muda na rotina do pet',
    resumo: 'Idade ideal, recuperação pós-cirúrgica e ajustes de alimentação depois do procedimento.',
    categoria: 'Saúde',
    data: '2026-08-26',
    autor: 'Dra. Paula Mendes — veterinária responsável',
    capa: capaBlog('adult-poodle.jpg'),
    publicado: true,
    conteudo:
      'A castração reduz o risco de tumores testiculares, de problemas prostáticos e facilita o controle de comportamento sexualizado. O período ideal varia de 6 a 12 meses conforme porte e评测 ração. A recuperação costuma levar de 10 a 14 dias, com restrição de escadas e exercícios. A partir da alta, é comum reduzir um terço da ração para evitar ganho de peso rápido.',
  },
  {
    id: 'post-16',
    titulo: 'Antipulgas: por que a proteção externa é obrigatória',
    resumo:
      'Entenda por que a proteção contra pulgas e carrapatos deve vir junto com o calendário antiparasitário.',
    categoria: 'Saúde',
    data: '2026-08-19',
    autor: 'Dra. Paula Mendes — veterinária responsável',
    capa: capaBlog('a-white-dog-lay-on-rock.jpg'),
    publicado: true,
    conteudo:
      'Pulgas e carrapatos funcionam como vetores de vermes. Um único animal infectado pode contaminar toda a casa em poucas semanas. Por isso, a aplicação externa ou oral contra ectoparasitas deve seguir um calendário próprio e ser mantida mesmo no inverno, quando a praga não aparece mas os animais continuam expostos.',
  },
  {
    id: 'post-17',
    titulo: 'Alimentação: a diferença entre porção e excesso',
    resumo: 'O erro mais comum na alimentação de pets não é o tipo de ração, é a quantidade servida.',
    categoria: 'Alimentação',
    data: '2026-08-12',
    autor: 'Equipe Canil de Vilhena',
    capa: capaBlog('agility-slalom-5.jpg'),
    publicado: true,
    conteudo:
      'A quantidade recomendada vem do peso ideal, não da fome do animal. Ração medida em copos, snacks limitados a uma pequena parte das calorias diárias e água fresca à vontade reduzem problemas digestivos e de peso. Trocas de alimentação devem ser graduais em sete a dez dias para preservar a flora intestinal.',
  },
  {
    id: 'post-18',
    titulo: 'Enriquecimento ambiental para gatos que ficam sozinhos',
    resumo: 'Brinquedos, prateleiras e janelas que transformam a espera em atividade mental.',
    categoria: 'Bem-estar',
    data: '2026-08-05',
    autor: 'Equipe Canil de Vilhena',
    capa: capaBlog('a-sleeping-young-tabby-cat.jpg'),
    publicado: true,
    conteudo:
      'Gatos que ficam sozinhos precisam de estímulo mental tanto quanto físico. Prateleiras em diferentes alturas, caixas de papelão, brinquedos com erva-gateira e janelas com vista para a rua transformam a espera em atividade. Locais com mudança frequente de layout exigem ainda mais atenção: nesses casos, o enriquecimento ajuda a reduzir的行为 stressful.',
  },
  {
    id: 'post-19',
    titulo: 'O que levar no primeiro dia pós-adoção',
    resumo: 'Documentos, transportador, ração e brinquedo: o kit essencial para a viagem de volta.',
    categoria: 'Adoção',
    data: '2026-07-29',
    autor: 'Equipe Canil de Vilhena',
    capa: capaBlog('a-dog-in-hambledon-hill.jpg'),
    publicado: true,
    conteudo:
      'No momento da adoção, a equipe entrega o histórico do animal, a carteira de vacinação e as orientações pós-adoção. Leve transportador adequado ao porte, uma muda de roupa com cheiro conhecido do animal, ração da casa e um brinquedo. Nada de passear no caminho: o trajeto deve ser tranquilo para reduzir a ansiedade inicial.',
  },
  {
    id: 'post-20',
    titulo: 'Banho e tosa: quando o banho em casa é seguro',
    resumo: 'Banho, secagem e tosa: os cuidados para não transformar a higiene em-estresse.',
    categoria: 'Bem-estar',
    data: '2026-07-22',
    autor: 'Equipe Canil de Vilhena',
    capa: capaBlog('a-golden-retriever-5-barras.jpg'),
    publicado: true,
    conteudo:
      'Banho de rotina fica tranquilo quando o animal já associa o procedimento a atividades prazerosas. Use água morna, shampoo neutro e seque bem as orelhas e entre os dedos. Para raças de pelo longo, o agendamento de tosa profissional a cada 6 a 8 semanas facilita o manejo diário.',
  },
  {
    id: 'post-21',
    titulo: 'Microchip e placa de identificação: por que os dois importam',
    resumo:
      'A microchipagem recupera animais perdidos; a placa avisa quem encontra. As duas ferramentas se complementam.',
    categoria: 'Cidadania',
    data: '2026-07-15',
    autor: 'Assessoria do Canil Municipal',
    capa: capaBlog('3-aar-golden-hund.jpg'),
    publicado: true,
    conteudo:
      'A placa reduz o tempo de recuperação porque avisa imediatamente quem encontra o animal. O microchip permite localizar o tutor em poucos minutos, desde que os dados estejam atualizados no sistema. O canil oferece microchipagem gratuita para animais adotados, com cadastro no momento da entrega.',
  },
  {
    id: 'post-22',
    titulo: 'Doação de ração: o que é prioritário neste momento',
    resumo: 'A equipe lista os itens com maior demanda para o abrigo e orienta como doar de forma segura.',
    categoria: 'Notícia',
    data: '2026-07-08',
    autor: 'Assessoria do Canil Municipal',
    capa: capaBlog('a-playful-set-of-dogs-on-a-beach.jpg'),
    publicado: true,
    conteudo:
      'A demanda por ração para cães adultos, areia higiênica, caixas de transporte e medicamentos veterinários aumenta nos períodos frios. Prefira doar em empresas com regularidade fiscal ou diretamente no canil. Descarte de medicamentos deve seguir a orientação da veterinária para evitar automedicação e Waiper Hearing.',
  },
];

const INTERESSES = [
  {
    id: 'int-seed-1',
    petId: 'pet-nina',
    petNome: 'Nina',
    nome: 'Fernanda Souza',
    whatsapp: '(69) 9 9154-2201',
    email: 'fernanda.souza@email.com',
    cidade: 'Vilhena - Centro',
    mensagem: 'Tenho rotina estável, casa com quintal seguro e experiência com cães de médio porte.',
    criadoEm: '2026-09-18T14:20:00.000Z',
    origem: 'site',
    statusAtendimento: 'visita agendada',
    prioridadeAtendimento: 'alta',
  },
  {
    id: 'int-seed-2',
    petId: 'pet-luna',
    petNome: 'Luna',
    nome: 'Ricardo Nunes',
    whatsapp: '(69) 9 9231-4409',
    email: 'ricardo.nunes@email.com',
    cidade: 'Vilhena - Bodanese',
    mensagem: 'Moro em apartamento, trabalho em home office e posso acompanhar a adaptação da gata com calma.',
    criadoEm: '2026-09-17T10:05:00.000Z',
    origem: 'site',
    statusAtendimento: 'contato realizado',
    prioridadeAtendimento: 'media',
  },
  {
    id: 'int-seed-3',
    petId: 'pet-simba',
    petNome: 'Simba',
    nome: 'João Pedro Lima',
    whatsapp: '(69) 9 9941-3312',
    email: 'joaopedro.lima@email.com',
    cidade: 'Vilhena - Jardim América',
    mensagem: 'Tenho espaço e disponibilidade para passeios diários. Família já aprovada para adoção.',
    criadoEm: '2026-09-16T17:48:00.000Z',
    origem: 'site',
    statusAtendimento: 'em triagem',
    prioridadeAtendimento: 'alta',
  },
  {
    id: 'int-seed-4',
    petId: 'pet-farofa',
    petNome: 'Farofa',
    nome: 'Camila Azevedo',
    whatsapp: '(69) 9 9811-2203',
    email: 'camila.azevedo@email.com',
    cidade: 'Vilhena - Cristo Rei',
    mensagem: 'Casa ampla, família presente e disponibilidade para acompanhamento veterinário inicial.',
    criadoEm: '2026-09-15T08:32:00.000Z',
    origem: 'site',
    statusAtendimento: 'novo',
    prioridadeAtendimento: 'media',
  },
  {
    id: 'int-seed-5',
    petId: 'pet-tobias',
    petNome: 'Tobias',
    nome: 'Marcos Aurélio',
    whatsapp: '(69) 9 9950-4410',
    email: 'marcos.aurelio@email.com',
    cidade: 'Vilhena - Jardim Eldorado',
    mensagem: 'Sou educador físico e pratico agility amador. Queria um cão para compartilhar essa rotina.',
    criadoEm: '2026-09-14T09:10:00.000Z',
    origem: 'site',
    statusAtendimento: 'concluido',
    prioridadeAtendimento: 'baixa',
  },
  {
    id: 'int-seed-6',
    petId: 'pet-maya',
    petNome: 'Maya',
    nome: 'Patrícia Nogueira',
    whatsapp: '(69) 9 9220-8815',
    email: 'patricia.nogueira@email.com',
    cidade: 'Vilhena - Setor Maringá',
    mensagem: 'Tenho gatos idosos em casa e busco companhia tranquila para os três.',
    criadoEm: '2026-09-13T16:25:00.000Z',
    origem: 'site',
    statusAtendimento: 'em triagem',
    prioridadeAtendimento: 'baixa',
  },
  {
    id: 'int-seed-7',
    petId: 'pet-apollo',
    petNome: 'Apolo',
    nome: 'Rafael Bittencourt',
    whatsapp: '(69) 9 9137-2266',
    email: 'rafael.bittencourt@email.com',
    cidade: 'Vilhena - Jardim Bandeirantes',
    mensagem: 'Tenho experiência com cães grandes e quintal amplo. Posso buscar no fim de semana.',
    criadoEm: '2026-09-12T11:40:00.000Z',
    origem: 'site',
    statusAtendimento: 'arquivado',
    prioridadeAtendimento: 'baixa',
  },
];

const DENUNCIAS = [
  {
    id: 'den-seed-1',
    local: 'Avenida Major Amarante, próximo à praça',
    descricao: 'Cachorro aparentemente abandonado há dois dias, sem coleira e com sinais de desnutrição.',
    contato: 'Ana Paula • (69) 9 9300-1188',
    origem: 'contato',
    statusAtendimento: 'equipe acionada',
    prioridadeAtendimento: 'alta',
    criadoEm: '2026-09-18T09:40:00.000Z',
  },
  {
    id: 'den-seed-2',
    local: 'Bairro Jardim Primavera, rua sem saída',
    descricao: 'Ninhada de gatos em terreno baldio, sem acesso regular a água e alimento.',
    contato: 'Rogério • (69) 9 9455-7722',
    origem: 'contato',
    statusAtendimento: 'em analise',
    prioridadeAtendimento: 'alta',
    criadoEm: '2026-09-17T16:12:00.000Z',
  },
  {
    id: 'den-seed-3',
    local: 'Setor 19, área de comércio',
    descricao: 'Animal com ferimento visível na pata traseira circulando entre veículos estacionados.',
    contato: '(69) 9 9110-5533',
    origem: 'contato',
    statusAtendimento: 'resolvida',
    prioridadeAtendimento: 'media',
    criadoEm: '2026-09-16T11:07:00.000Z',
  },
  {
    id: 'den-seed-4',
    local: 'Bairro Cidade Nova, lote sem 地址',
    descricao: 'Cães soltos no terreno, sem responsável aparente e com acesso livre à via principal.',
    contato: 'Jussara • (69) 9 9620-4417',
    origem: 'contato',
    statusAtendimento: 'nova',
    prioridadeAtendimento: 'media',
    criadoEm: '2026-09-15T19:05:00.000Z',
  },
];

const USUARIOS = [
  {
    id: 'usr-admin',
    nome: 'Administrador do Sistema',
    login: 'admin',
    senhaHash: Buffer.from('admin123').toString('base64'),
    perfil: 'admin',
    ativo: true,
    cargo: 'Secretaria de Meio Ambiente',
    email: 'meioambiente@vilhena.ro.gov.br',
    cpf: '000.000.001-00',
    telefone: '(69) 9 9999-0000',
    criadoEm: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'usr-vet',
    nome: 'Dra. Paula Mendes',
    login: 'paula.vet',
    senhaHash: Buffer.from('vet12345').toString('base64'),
    perfil: 'veterinario',
    ativo: true,
    cargo: 'Veterinária responsável',
    email: 'paula.mendes@vilhena.ro.gov.br',
    cpf: '000.000.002-00',
    telefone: '(69) 9 9888-1122',
    criadoEm: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'usr-atend',
    nome: 'Carlos Eduardo Lima',
    login: 'carlos.atend',
    senhaHash: Buffer.from('atend123').toString('base64'),
    perfil: 'atendente',
    ativo: true,
    cargo: 'Atendente do canil',
    email: 'carlos.lima@vilhena.ro.gov.br',
    cpf: '000.000.003-00',
    telefone: '(69) 9 9777-3344',
    criadoEm: '2026-02-01T00:00:00.000Z',
  },
];

const AUDITORIA = [
  {
    id: 'audit-seed-1',
    acao: 'criar',
    entidade: 'pet',
    alvoId: 'pet-maya',
    detalhes: 'Pet Maya cadastrado pelo sistema.',
    usuarioId: 'usr-vet',
    usuarioNome: 'Dra. Paula Mendes',
    usuarioLogin: 'paula.vet',
    usuarioPerfil: 'veterinario',
    criadoEm: '2026-09-06T09:40:00.000Z',
    metadados: null,
  },
  {
    id: 'audit-seed-2',
    acao: 'publicar',
    entidade: 'historia',
    alvoId: 'pet-amelie',
    detalhes: 'História de adoção de Amélie publicada no site.',
    usuarioId: 'usr-admin',
    usuarioNome: 'Administrador do Sistema',
    usuarioLogin: 'admin',
    usuarioPerfil: 'admin',
    criadoEm: '2026-08-28T11:10:00.000Z',
    metadados: null,
  },
  {
    id: 'audit-seed-3',
    acao: 'editar',
    entidade: 'interesse',
    alvoId: 'int-seed-1',
    detalhes: 'Etapa alterada para Visita agendada.',
    usuarioId: 'usr-atend',
    usuarioNome: 'Carlos Eduardo Lima',
    usuarioLogin: 'carlos.atend',
    usuarioPerfil: 'atendente',
    criadoEm: '2026-09-18T15:10:00.000Z',
    metadados: null,
  },
];

const DEPOIMENTOS = [
  {
    nome: 'Larissa e Thor',
    foto: 'uploads/pets/a-golden-retriever-barras.jpg',
    texto:
      'Adotar pelo Canil de Vilhena foi acolhedor e organizado. O Thor chegou com tudo explicado e hoje é parte da família.',
  },
  {
    nome: 'Família Rocha e Mel',
    foto: 'uploads/pets/agility-sprung-schafer-2.jpg',
    texto:
      'A equipe ajudou no processo inteiro e acompanhou os primeiros dias. A Mel está super adaptada com as crianças.',
  },
  {
    nome: 'Bruno e Nala',
    foto: 'uploads/pets/cats-kitten-jerusalem.jpg',
    texto:
      'Eu tinha dúvidas sobre rotina em apartamento e o blog ajudou demais. A Nala se tornou meu xodó.',
  },
];

// As datas acima foram escritas em datas fixas. Como o painel filtra por
// período (padrão: últimos 90 dias) e mostra séries mensais, redistribuímos
// tudo em torno de "hois": pets resgatados ao longo do último ano, com a
// maioria nos últimos meses, eavityos mais recentes.
const DIA = 24 * 60 * 60 * 1000;

function iso(diasAtras, horas = 9) {
  const momento = new Date(Date.now() - diasAtras * DIA);
  momento.setHours(horas, Math.floor((diasAtras * 37) % 60), 0, 0);
  return momento.toISOString();
}

function Curva(expoente, totalDias, deslocamentoMinimo) {
  return (indice, quantidade) => {
    const posicao = quantidade <= 1 ? 1 : indice / (quantidade - 1);
    const restante = Math.pow(1 - posicao, expoente);
    return Math.round(deslocamentoMinimo + restante * (totalDias - deslocamentoMinimo));
  };
}

function alinharDatasNoPresente() {
  const curvaLarga = Curva(2, 320, 2);
  const curvaPosts = Curva(1.5, 130, 2);
  const curvaFluxo = Curva(1.2, 50, 1);

  PETS.forEach((pet, indice) => {
    const criado = curvaLarga(indice, PETS.length);
    pet.criadoEm = iso(criado, 9);
    pet.atualizadoEm = iso(Math.max(0, criado - Math.round(criado / 4)), 15);

    if (pet.historiaPublicado && !pet.historiaPublicadoEm) {
      pet.historiaPublicadoEm = iso(Math.max(0, criado - 10), 11);
      pet.historiaAtualizadoEm = pet.historiaPublicadoEm;
    }
  });

  POSTS.forEach((post, indice) => {
    post.data = iso(curvaPosts(indice, POSTS.length), 8);
  });

  INTERESSES.forEach((item, indice) => {
    item.criadoEm = iso(curvaFluxo(indice, INTERESSES.length) + indice, 10);
  });

  DENUNCIAS.forEach((item, indice) => {
    item.criadoEm = iso(curvaFluxo(indice, DENUNCIAS.length) * 2, 8);
  });

  AUDITORIA.forEach((item, indice) => {
    item.criadoEm = iso(indice, 10);
  });
}

alinharDatasNoPresente();

module.exports = { PETS, POSTS, INTERESSES, DENUNCIAS, USUARIOS, AUDITORIA, DEPOIMENTOS };